export const personalInfo = {
  mail: "mailto:gabyreload@gmail.com",
  whatsapp: "https://web.whatsapp.com/send?l=es&phone=+5493476643800",
  github: "https://github.com/gabyreload1983",
  linkedin: "https://www.linkedin.com/in/estebangabrielgodoy/",
  instagram: "https://www.instagram.com/estebangabrielgodoy/",
  youtube: "https://www.youtube.com/channel/UClaO3kGHGcGWOPzGH--hIaQ/videos",
};

export const projects = [
  {
    nameImage: "vidly",
    name: "Vidly",
    type: "Web Application",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP", "REACT"],
    urlGithub: "https://github.com/gabyreload1983/vidly-frontend",
    urlDeploy: "https://vidly-frontend.vercel.app/movies",
  },
  {
    nameImage: "tenzies",
    name: "Tenzies",
    type: "Web Application Game",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP", "REACT"],
    urlGithub: "https://github.com/gabyreload1983/React-dices-game",
    urlDeploy: "https://gabyreload-tenzie.netlify.app/",
  },
  {
    nameImage: "login",
    name: "Login",
    type: "Web Application",
    technologies: [
      "HTML",
      "CSS",
      "JAVASCRIPT",
      "BOOTSTRAP",
      "NODEJS",
      "EXPRESS",
      "MONGODB",
    ],
    urlGithub: "https://github.com/gabyreload1983/NodeJs-Login",
    urlDeploy: "https://gabyreload-nodejs-login.herokuapp.com/",
  },
  {
    nameImage: "notes",
    name: "Notes Blog",
    type: "Web Application",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "NODEJS", "EXPRESS", "MONGODB"],
    urlGithub: "https://github.com/gabyreload1983/NodeJs-Notas",
    urlDeploy: "https://reloadnotes.herokuapp.com/",
  },
  {
    nameImage: "sinapsis",
    name: "Sinapsis App",
    type: "Web Application",
    technologies: [
      "HTML",
      "CSS",
      "JAVASCRIPT",
      "BOOTSTRAP",
      "NODEJS",
      "EXPRESS",
      "MONGODB",
      "MYSQL",
    ],
    urlGithub: "https://github.com/gabyreload1983/app-sinapsis",
    urlDeploy: "",
  },
  {
    nameImage: "moshify",
    name: "Moshify",
    type: "Web Page",
    technologies: ["HTML", "CSS", "BOOTSTRAP"],
    urlGithub: "https://github.com/gabyreload1983/Moshify",
    urlDeploy: "https://proyectomosh.netlify.app/",
  },
  {
    nameImage: "estudio",
    name: "Estudio Contable Mugica",
    type: "Web Page",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP", "JAVASCRIPT"],
    urlGithub: "https://github.com/gabyreload1983/Estudio-Contable-Mugica",
    urlDeploy: "https://estudio-contable-mugica.vercel.app/",
  },
];
